/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import BDD.ConexionBDD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;


/**
 *
 * @author Eric
 */
public class FormularioDatos extends javax.swing.JPanel {

    /**
     * Creates new form FormularioDatos
     */
    ConexionBDD conn = new ConexionBDD();
    public void guardarDatos(){
        
        String nombre = TxtNombre.getText();
        String apellido = TxtApellido.getText();
        String DNIo = LabelDni.getText();
        String direccion = TxtDireccion.getText();
        String telefono = TxtTelefono.getText();
        String email = TxtEmail.getText();
            
        try{
            //Funcion para guardar los datos!
            Connection c = conn.conectar();
            PreparedStatement guardarDatos = c.prepareStatement("UPDATE somhue SET nombre='"+nombre+"',apellido='"+apellido+"',direccion='"+direccion+"',telefono='"+telefono+"',email='"+email+"'WHERE hueDNI='"+DNIo+"'");
            
            guardarDatos.execute();
            guardarDatos.close();
            
            
            //this.setVisible(false);
        }catch(SQLException e){
            
            System.err.println("Error al guardar los datos " + e);
            LabelAviso.setText("Los datos no pudieron guardarse");
            
        }finally{
            conn.desconectar();
            LabelAviso.setText("Los datos se guardaron con exito!");
            BtnAceptar.setEnabled(false);
           
        }  
        
    
    
    
    }
    public FormularioDatos() {
        initComponents();
        this.setLocation(null);
        try{
        
        Connection c = conn.conectar();
            PreparedStatement ultimoID = c.prepareStatement("SELECT MAX(id) FROM somhue");
            ResultSet rs = ultimoID.executeQuery();
            if(rs.next()){
              String ID = rs.getString(1);
              PreparedStatement recuperardni = c.prepareStatement("SELECT hueDNI FROM somhue WHERE id = '"+ID+"'");
              ResultSet n = recuperardni.executeQuery();
              if(n.next()){
                  String DNI = n.getString(1);
                  LabelDni.setText(DNI);
                  
              }
              
            }
            
        }catch(SQLException e){
            System.err.println("Error al guardar los datos " + e);
        }finally{
            conn.desconectar();
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelDni = new javax.swing.JLabel();
        LabelNombre = new javax.swing.JLabel();
        LabelApellido = new javax.swing.JLabel();
        LabelDireccion = new javax.swing.JLabel();
        LabelTelefono = new javax.swing.JLabel();
        LabelEmail = new javax.swing.JLabel();
        BtnSalir = new javax.swing.JButton();
        BtnAceptar = new javax.swing.JButton();
        TxtNombre = new javax.swing.JTextField();
        TxtApellido = new javax.swing.JTextField();
        TxtDireccion = new javax.swing.JTextField();
        TxtTelefono = new javax.swing.JTextField();
        TxtEmail = new javax.swing.JTextField();
        LabelDNI = new javax.swing.JLabel();
        LabelAviso = new javax.swing.JLabel();

        LabelDni.setText("DNI");

        LabelNombre.setText("Nombre");

        LabelApellido.setText("Apellido");

        LabelDireccion.setText("Direccion");

        LabelTelefono.setText("Telefono");

        LabelEmail.setText("Email");

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        BtnAceptar.setText("Aceptar");
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });

        TxtNombre.setText("Nombre");

        TxtApellido.setText("Apellido");

        TxtDireccion.setText("Direccion");

        TxtTelefono.setText("Telefono");

        TxtEmail.setText("Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelApellido)
                        .addGap(57, 57, 57)
                        .addComponent(TxtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelDireccion)
                        .addGap(48, 48, 48)
                        .addComponent(TxtDireccion))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelTelefono)
                        .addGap(53, 53, 53)
                        .addComponent(TxtTelefono))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelNombre)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(TxtNombre)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelEmail)
                        .addGap(71, 71, 71)
                        .addComponent(TxtEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelDni)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnSalir)
                        .addGap(18, 18, 18)
                        .addComponent(LabelAviso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnAceptar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDni)
                    .addComponent(LabelDNI))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNombre)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelApellido)
                    .addComponent(TxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDireccion)
                    .addComponent(TxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTelefono)
                    .addComponent(TxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEmail)
                    .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSalir)
                    .addComponent(BtnAceptar)
                    .addComponent(LabelAviso))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        // TODO add your handling code here:
        guardarDatos();
    }//GEN-LAST:event_BtnAceptarActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_BtnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JLabel LabelApellido;
    private javax.swing.JLabel LabelAviso;
    private javax.swing.JLabel LabelDNI;
    private javax.swing.JLabel LabelDireccion;
    private javax.swing.JLabel LabelDni;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelTelefono;
    private javax.swing.JTextField TxtApellido;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtTelefono;
    // End of variables declaration//GEN-END:variables
}
